### ISSUE TITLE
сохранение дел

### ISSUE THREAD

**Issue by isakura313** [adiabata/todo#3]
Было бы круто переделать код, что бы при закрытии браузера это записывалось в localStorage. Закрываем браузер, потом открываем приложеньку, а там все дела остались. Превращает из игрушки хоть во что-то стоящее.
Хотя это все усложнит, + не очень полезно  и нечасто используется https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API

**Comment by snufffkin** [comment]
нет, нахуй, сделаем с бд лучше сразу. какой им резон будет переписывать примерно тот же функционал еще раз.
